### ISSUE TITLE
Exception handler should not use hard-coded reference to email address.

### ISSUE THREAD

**Issue by ist-pasha** [baracudda/androidBits#4]
The `ReportAnExceptionHandler` should provide methods by which the consumer can pass in any string for use as an email address, rather than depending on a magic resource ID `R.string.postmortem_report_email_recipients`. However, for backward compatibility, this resource reference should still be the default value if no other string is specified by the consumer.

**Comment by baracudda** [comment]
This class was intended as a way for the author of the app to get reports
from the field without having the user specify an email address first.
However, I also see there are a few cases where a specific string resource
may not be the best or only approach desired.

On Wed, Feb 24, 2016 at 3:41 PM, Pasha Paterson notifications@github.com
wrote:

> The ReportAnExceptionHandler should provide methods by which the consumer
> can pass in any string for use as an email address, rather than depending
> on a magic resource ID R.string.postmortem_report_email_recipients.
> However, for backward compatibility, this resource reference should still
> be the default value if no other string is specified by the consumer.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/baracudda/androidBits/issues/4.

## 

Ryan Fischbach
www.istresearch.com
931.320.9653

## 

---

This e-mail and any files transmitted with it may be proprietary and are 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this e-mail in error please notify the 
sender. Please note that any views or opinions presented in this e-mail are 
solely those of the author and do not necessarily represent those of IST 
Research. The recipient should check this e-mail and any attachments for 
the presence of viruses. IST Research accepts no liability for any damage 
caused by any virus transmitted by this e-mail.
